parking/basic/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.registerPage,name='registerPage'),
    path('', views.loginPage,name='loginPage'),
    path('login/', views.loginPage,name='loginPage'),
    path('logout/', views.logoutPage,name='logoutPage'),
    path('user/',views.userPage,name='userPage'),
    path('myTicket/',views.myTicket,name='myTicket')
]

parking/parking/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('basic.urls'),name="basic"),
    path('vehiclecategory/',include('vehiclecategory.urls'),name="vehicle_category"),
    path('ticket/',include('ticket.urls'),name="ticket"),
    path('analysis/',include('analysis.urls'),name='analysis'),
    path('managevehicle/',include('managevehicle.urls'),name='manage_vehicle'),
    path('searchvehicle/',include('searchvehicle.urls'),name="search_vehicle"),
    path('slot/',include('slot.urls'),name="slot"),
    path('timeup/',include('timeup.urls'),name="timeup")
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

parking/slot/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.slot,name="slot"),
    path('createSlot/',views.createSlot,name='createSlot'),
    path('updateSlot/<str:pk>/',views.updateSlot,name='updateSlot'),
    path('deleteSlot/<str:pk>/',views.deleteSlot,name='deleteSlot'),
]

parking/basic/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class  Profile(models.Model):
    user = models.OneToOneField(User,null=True,blank=True,on_delete=models.CASCADE)
    phone = models.CharField(max_length=12,null=True,default='')
    profile_pic = models.ImageField(default='profile.nef',null=True,blank=True)
    date = models.DateTimeField(auto_now_add=True,null=True)

    def __str__(self):
        return str(self.user)

parking/basic/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from .models import Profile

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields ='__all__'
        exclude = ['user']

parking/basic/views.py
from django.core.checks import messages
from django.forms.models import model_to_dict
from django.shortcuts import redirect, render
from .forms import ProfileForm
from django.contrib.auth.models import Group
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from .decorators import unauthenticated_user,allowed_users
from django.contrib.auth.decorators import login_required
from .models import Profile
from ticket.models import Ticket
# Create your views here.




@unauthenticated_user
def registerPage(request):
    if request.method == "POST":
        username = request.POST['user_name'].upper()
        email = request.POST['email'].upper()
        phone = request.POST['phone_number']
        pass1 = request.POST['password1']
        pass2 = request.POST['password2']
        try:
            if pass1==pass2 and len(pass1)>8:
                if not User.objects.filter(email=email):
                    myuser = User.objects.create_user(username,email,pass1)
                    user = myuser
                    group = Group.objects.get(name='customer')
                    user.groups.add(group)
                    myuser.save()
                    Profile.objects.create(
                        user=myuser,
                        phone = phone
                    )
                    return redirect('loginPage')
                else:
                    return render(request,'basic/register.html',{'messages':'Email  is not unique please check '})
            else:
                return render(request,'basic/register.html',{'messages':'password is not same or password length is small'})
        except Exception as e:
            return render(request,'basic/register.html',{'messages':'Please enter unique username'})
    return render(request,'basic/register.html')


@unauthenticated_user
def loginPage(request):
    if request.method=='POST':
        username = request.POST['username'].upper()
        password = request.POST['password']
        user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return redirect('/ticket')
        else:
            messages.info(request,'Username or password is incorrect')
            return render(request,'basic/login.html')
    return render(request,'basic/login.html')

@login_required(login_url='/login')
@allowed_users(allowed_roles=['manager','watchman','customer','admin'])
def logoutPage(request):
    logout(request)
    return redirect('/login')

@login_required(login_url='/login')
@allowed_users(allowed_roles=['customer'])
def userPage(request):
    user = User.objects.get(username=request.user)
    profile = Profile.objects.get(user = user)
    form = ProfileForm(instance=request.user.profile)
    if request.method == 'POST':
        form = ProfileForm(request.POST,request.FILES,instance=request.user.profile) 
        if form.is_valid():
            form.save()
            messages.info(request,'successfully updated profile')
    return render(request,'basic/user.html',{'form':form,'user':user})

@login_required(login_url='/login')
@allowed_users(allowed_roles=['customer'])
def myTicket(request):
    user = request.user
    profile = Profile.objects.get(user=user).phone
    ticket = Ticket.objects.filter(phone_number=profile)
    return render(request,'basic/myticket.html',{'ticket':ticket})

parking/basic/templates/basic/login.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Login</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
			
		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}
	</style>

</head>
<body>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
				<div class="d-flex justify-content-center">


					<h3 id="form-title">LOGIN</h3>
				</div>
				<div class="d-flex justify-content-center form_container">
					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name="username" placeholder="Username..." class="form-control">
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
								<input type="password" name="password" placeholder="Password..." class="form-control" >
						</div>

							<div class="d-flex justify-content-center mt-3 login_container">
				 				<input class="btn login_btn" type="submit" value="Login">
				   			</div>
					</form>

                </div>
                {% for message in messages %}
                    <p id='messages'>{{message}}</p>
                {% endfor %}
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Don't have an account? <a href="{% url 'registerPage' %}" class="ml-2">Sign Up</a>
					</div>
			
				</div>
			</div>
		</div>
	</div>
</body>

</html>

parking/basic/templates/basic/main.html
<!DOCTYPE html>
<html>
<head>
	<title>CRM</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	
<style>
	#ink{
		background-color: rgb(108, 233, 233);
	}
	.error-main{
	background-color: #fff;
	box-shadow: 0px 10px 10px -10px #5D6572;
	}
	.error-main h1{
	font-weight: bold;
	color: #444444;
	font-size: 100px;
	text-shadow: 2px 4px 5px #6E6E6E;
	}
	.error-main h6{
	color: #42494F;
	}
	.error-main p{
	color: #9897A0;
	font-size: 14px; 
	}
</style>
</head>
<body>
	{%  include 'analysis/navbar.html' %}

	<hr>


	{% block content %}	
	{% endblock %}

	
	<hr>
	
</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

parking/basic/templates/basic/myticket.html
{%  extends 'basic/main.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <div class="col-md ">
                <h3>My Booked ticket :</h3>
                <hr>
                <div class="row " id="ink">
                    <div class="col">Ticket Id</div>
                    <div class="col">Type</div>
                    <div class="col">Date</div>
                    <div class="col">Vehicle Number</div>
                    <div class="col">Slot Name</div>
                    <div class="col">Valid time </div>
                </div>
            </div>
            <br>
            {% for i in ticket %}
                <div class="col-md">
                    <div class="row">
                        <div class="col">{{i.ticket_id}}</div>
                        <div class="col">{{i.vehicle_type}}</div>
                        <div class="col">{{i.date}}</div>
                        <div class="col">{{i.vehicle_number}}</div>
                        <div class="col">{{i.slot}}</div>
                        <div class="col">{{i.valid_time}} </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

parking/basic/templates/basic/register.html
<!DOCTYPE html>
<html>
    
<head>
	<title>Register</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

	<style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #7abecc !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;
		}
		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

	</style>

</head>
<body>  
    <div class="container">
            {% if messages %}
            {{ messages }}
            {% endif %}
    </div>
	<div class="container h-100">
		<div class="d-flex justify-content-center h-100">
            
			<div class="user_card">
				<div class="d-flex justify-content-center">
					<h3 id="form-title">REGISTER ACCOUNT</h3>
				</div>
				<div class="d-flex justify-content-center form_container">

					<form method="POST" action="">
                        {% csrf_token %}
						<div class="input-group mb-3">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-user"></i></span>
							</div>
							<input type="text" name='user_name'>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							<input type="email" name='email'>
                        </div>
                        <div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-envelope-square"></i></span>
							</div>
							<input type="text" name='phone_number'>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name='password1'>
						</div>
						<div class="input-group mb-2">
							<div class="input-group-append">
								<span class="input-group-text"><i class="fas fa-key"></i></span>
							</div>
							<input type="password" name='password2'>
                        </div>

				   		<div class="d-flex justify-content-center mt-3 login_container">
				 			<input class="btn login_btn" type="submit" value="Register Account">
				   		</div>
					</form>
				</div>
		
				<div class="mt-4">
					<div class="d-flex justify-content-center links">
						Already have an account? <a href="{% url 'loginPage' %}" class="ml-2">Login</a>
					</div>
				</div>
			</div>
		</div>
	</div>
	<script>
						/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field 
		 */

		//Query All input fields
		var form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Username..';
		form_fields[2].placeholder='Email..';
		form_fields[3].placeholder='Phone number..';
		form_fields[4].placeholder='Enter password...';
		form_fields[5].placeholder='Re-enter Password...';


		for (var field in form_fields){	
			form_fields[field].className += ' form-control'
		}
	</script>
</body>
</html>

parking/basic/templates/basic/user.html
{%  extends 'basic/main.html' %}
{% block content %}

<style>
	.profile-pic{
		max-width: 200px;
		max-height:200px;
		margin: 0 auto;
		border-radius: 50%;
	}
</style>
		<div class="card center">
			{% for message in messages %}
			<p id='messages'>{{message}}</p>
			{% endfor %}
		</div>
<hr>
<div class="row">

	<div class="col-md-3">
		<div class="card card-body">
			<a class="btn btn-warning" href="/ticket"> &#8592; Back to Ticket</a>
			<hr>
			<h3 style="text-align: center">Account Settings</h3>
			<hr>
			<img class="profile-pic" src="{{request.user.profile.profile_pic.url}}" >
		</div>
    </div>
    
	<div class="col-md-9">
		<div class="card card-body">
			<form method="POST" action="" enctype="multipart/form-data">
				{% csrf_token %}
				<p>
					<label >UserName : {{user.username}}</label> 
				</p>
				<p>
					<label >UserEmail : {{user.email}}</label> 
				</p>
				<p>
					<label for="id_phone">Phone:</label> <input type="text" name="phone" value="9876543215" maxlength="12" required="" id="id_phone">
				</p>
				<p>
					<label for="id_profile_pic">Profile pic:</label> <input type="file" name="profile_pic" accept="image/*" id="id_profile_pic">
				</p>
			    <input class="btn btn-primary" type="submit" name="Update Information">
			</form>
		</div>
    </div>
    
</div>

{% endblock %}